# Generated by Django 3.0.5 on 2020-04-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_details', '0002_auto_20200417_0418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
