# Generated by Django 3.0.5 on 2020-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_details', '0004_studentsmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='English',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='Maths',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='Science',
            new_name='science',
        ),
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='Socialscience',
            new_name='socialscience',
        ),
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='Tamil',
            new_name='tamil',
        ),
        migrations.RenameField(
            model_name='studentsmarks',
            old_name='Total_Marks',
            new_name='total_marks',
        ),
    ]
